name: iSnap
options:
  bundleIdPrefix: dev.isnap
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    MACOSX_DEPLOYMENT_TARGET: 14.0
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: TXD67UY7X2
    ENABLE_HARDENED_RUNTIME: YES
targets:
  iSnap:
    type: application
    platform: macOS
    sources:
      - Sources/iSnap
      - path: Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.isnap.app
        PRODUCT_NAME: iSnap
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/iSnap/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Sources/iSnap/Resources/iSnap.entitlements
    dependencies:
      - target: iSnapWidget
        embed: true
    scheme:
      testTargets:
        - iSnapTests
  iSnapWidget:
    type: app-extension
    platform: macOS
    sources:
      - Sources/iSnapWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.isnap.app.widget
        PRODUCT_NAME: iSnapWidget
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/iSnapWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/iSnapWidget/iSnapWidget.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES
        SKIP_INSTALL: YES
  iSnapTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/iSnapTests
    dependencies:
      - target: iSnap
